### ISSUE TITLE
Build failed using 2.5.0

### ISSUE THREAD

**Issue by iqbal0304** [shripalsoni04/nativescript-angular-drawer-template#10]
I'm using 2.5.0 and got this. What am I missing here? Thanks :D

D:\nativescript\drawer-project\platforms\android\build\intermediates\manifests\full\F0F1\debug\AndroidManifest.xml:22:23-37: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/icon').

:processF0F1DebugResources FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':processF0F1DebugResources'.
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Android\android-sdk\build-tools\25.0.2\aapt.exe'' finished with non-zero exit value 1
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 17.23 secs
Command D:\nativescript\drawer-project\platforms\android\gradlew.bat failed with exit code 1

**Comment by dzfweb** [comment]
i have this problem too.

**Comment by iqbal0304** [comment]
After copying AndoidManifest.xml file and icon.png from Groceries sample, the error is disappear an I can build the project. But when I run it, nothing is loaded in the genymotion.

Here are the tns run android output

Executing before-watch hook from D:\nativescript\HazardApp\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.1.6
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
W/System.err( 1947):    at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 1947):    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
W/System.err( 1947):    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
W/System.err( 1947):    at com.tns.Runtime.callJSMethod(Runtime.java:1047)
W/System.err( 1947):    at com.tns.Runtime.callJSMethod(Runtime.java:1028)
W/System.err( 1947):    at com.tns.Runtime.callJSMethod(Runtime.java:1018)
W/System.err( 1947):    at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 1947):    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
W/System.err( 1947):    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
W/System.err( 1947):    at com.tns.Runtime.callJSMethod(Runtime.java:1047)
W/System.err( 1947):    at com.tns.Runtime.callJSMethod(Runtime.java:1028)
W/System.err( 1947):    at com.tns.Runtime.callJSMethod(Runtime.java:1018)
2:27:29 PM - Compilation complete. Watching for file changes.

**Comment by prolink007** [comment]
Fixed in my [pull request](https://github.com/shripalsoni04/nativescript-angular-drawer-template/pull/11).

**Comment by shripalsoni04** [comment]
@prolink007 , Thanks for PR 👍 

I have merged your code. I also found that in new nativescript version the default App_Resource folder is not getting created. So I have merged the whole default App_Resource folder inside this template. 

I have tested this on Android and iOS and it is working fine now. These fixes are available in version 1.2.2.

Thanks All.

**Comment by prolink007** [comment]
@shripalsoni04 No problem.
