### ISSUE TITLE
JS ERROR Error: No NgModule metadata found for 'AppModule'.

### ISSUE THREAD

**Issue by wesleysteverson** [shripalsoni04/nativescript-angular-drawer-template#19]
Before tns create my-project-name --template nativescript-angular-drawer-template
and tns run ios..

error:

<img width="1280" alt="captura de tela 2017-05-23 as 13 13 20" src="https://cloud.githubusercontent.com/assets/6559140/26364184/d957e2e6-3fb9-11e7-844e-727f7bc3ecf6.png">

**Comment by shripalsoni04** [comment]
@wesleysteverson , I have published v2.0.0 with angular (~4.0), nativescript (~3.0) and nativescript-telerik-ui (~2.0) versions.

I have tested this new template on Android and iOS and it is working fine now.

You can try creating new project with this template by executing command:
`tns create my-project-name --template nativescript-angular-drawer-template`

Thanks
