### ISSUE TITLE
Menu does not slide if list is long

### ISSUE THREAD

**Issue by leocrawf** [shripalsoni04/nativescript-angular-drawer-template#3]
I compared this to the nativescript theme. One of the important differences is that the menu does not slide up or down as needed if the list is too long. I tried adding a ScrollView but it did not scroll. Any suggestions on how to make the menu list scrollable?

**Comment by shripalsoni04** [comment]
Thanks for bringing this to my notice. I have wrapped `.sidedrawer-content`  element inside `ScrollView` and have tested it with more links. It is working fine now. 

This change is published with 1.1.0 version of `nativescript-angular-drawer-template` package.

For reference I have created a [demo app](https://github.com/shripalsoni04/ns-ng-drawer-template-demo) which has menu scrollable.

**Comment by shripalsoni04** [comment]
Considering this as resolved. If any issue feel free to reopen.
