### ISSUE TITLE
Start up time on android very slow

### ISSUE THREAD

**Issue by leocrawf** [shripalsoni04/nativescript-angular-drawer-template#6]
Hello I build an app using this starter template for a school. Its my first nativescript app. All works well except the start up takes 15 seconds. I have already ugraded to tns module 2.4 which has greatly improved the navigation and overall app response but load time is still a problem. I have read this article here https://www.nativescript.org/blog/optimizing-app-loading-time-with-angular-2-lazy-loading and trying to see how difficult it would be to implement the easiest method which appears to be "callback-loading"?

**Comment by shripalsoni04** [comment]
Callback-loading should not be difficult. Just instead of configuring `component:` in routes, you need to use `loadChildren` with the component file and name as explained in the link you mentioned.

**Comment by leocrawf** [comment]
Ok. I will give it a try.
