### ISSUE TITLE
Change menu icon

### ISSUE THREAD

**Issue by rogerioleal1** [shripalsoni04/nativescript-angular-drawer-template#7]
Hello, I'm starting with nativescript, I would like to know how to change the icon from "drawer" to a white background.

![screenshot from 2016-12-09 14 55 05](https://cloud.githubusercontent.com/assets/4643449/21059058/8bc8446a-be1f-11e6-8837-7d77f42d3188.png)

**Comment by shripalsoni04** [comment]
To change drawer icon to white, follow below steps:

1. Download white drawer icon files from https://material.io/icons/#ic_menu, and put that into App_Resources/Android and App_Resources/iOS folders similar to how I have put ic_menu_black.png. You can use any icon library, but as that black drawer icon is from md, I have given that link
2. Use the white drawer icon by changing icon file name with your new icon file name at this line: https://github.com/shripalsoni04/nativescript-angular-drawer-template/blob/master/modules/shared/side-drawer-page/side-drawer-page.component.ts#L114

**Comment by rogerioleal1** [comment]
I changed the icon:

```
private getNavigationButton() {
        let navActionItem = new ActionItem();
        navActionItem.icon = 'res://ic_menu_white_24dp';
        //navActionItem.icon = 'res://ic_menu_black';

        if (navActionItem.ios) {
            navActionItem.ios.position = 'left';
        }

        navActionItem.on('tap', this.toggleDrawer.bind(this));
        return navActionItem;
    }

```

And placed the icon in the respective folders.

![screenshot from 2016-12-09 16 11 55](https://cloud.githubusercontent.com/assets/4643449/21061255/4515a3fe-be2a-11e6-86b4-b085147e3d8b.png)

The icon was not visible.
Rode the command tns livesync android --emulator --watch

![screenshot from 2016-12-09 16 12 10](https://cloud.githubusercontent.com/assets/4643449/21061269/4cf40b88-be2a-11e6-98de-6610c17c9147.png)


Any other tips?

**Comment by shripalsoni04** [comment]
Once you do any changes in App_Resources folder, you need to build and run the application as livesync will not be able to pick it up.

So instead of `livesync` command, execute `tns run android` or `tns run ios`

**Comment by rogerioleal1** [comment]
Worked perfectly.

Thank you very much.

![screenshot from 2016-12-09 16 30 10](https://cloud.githubusercontent.com/assets/4643449/21061824/c7024e42-be2c-11e6-8be7-82cd12faa8c8.png)

**Comment by eddy2enam** [comment]
how to add icon to sidebar list
