### ISSUE TITLE
when app load i get this error and toggle button not work 

### ISSUE THREAD

**Issue by mostafa-raafat** [shripalsoni04/nativescript-angular-drawer-template#8]
```
EXCEPTION: Uncaught (in promise): TypeError: v._nativeView.setCornerRadius is not a function
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): TypeError: v._nativeView.setCornerRadius is not a function
JS:     at resolvePromise (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:416:31)
JS:     at /data/data/org.nativescript.sidedrawer/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:393:13
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:190:28)
JS:     at Object.onInvoke (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/@angular/core/bundles/core.umd.js:6206:41)
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:189:34)
JS:     at Zone.run (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:83:43)
JS:     at /data/data/org.nativescript.sidedrawer/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:57
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:37)
JS:     at Object.onInvokeTask (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/@angular/core/bundles/core.umd.js:6197:41)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:42)
JS: Unhandled Promise rejection: v._nativeView.setCornerRadius is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: v._nativeView.setCornerRadius is not a function TypeError: v._nativeView.setCornerRadius is not a function
JS:     at StylePropertyChangedHandler.ImageStyler.setBorderRadiusProperty [as _applyProperty] (/data/data/org.nativescript.sidedrawer/files/app/tns_modules/ui/image/image.js:72:23)
```

**Comment by mahaboobbasha638** [comment]
i am also facing same issue... Any one fixed..

**Comment by hugohomesquita** [comment]
i am also facing same issue... Any fix for this?

**Comment by shripalsoni04** [comment]
I have upgraded versions of various dependencies of this starter template. I have tested this with latest `nativescript` (v2.4.2) and `tns-core-modules` (v2.4.4) on both Android and iOS. It is working without any issues.

Can you please test it again with this new version by executing below commnad:
`tns create my-project-name --template nativescript-angular-drawer-template`

**Comment by iqbal0304** [comment]
I'm using 2.5.0 and got this. What am I missing here? Thanks :D

D:\nativescript\drawer-project\platforms\android\build\intermediates\manifests\full\F0F1\debug\AndroidManifest.xml:22:23-37: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/icon').

:processF0F1DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Android\android-sdk\build-tools\25.0.2\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.23 secs
Command D:\nativescript\drawer-project\platforms\android\gradlew.bat failed with exit code 1

**Comment by shripalsoni04** [comment]
Assuming this to be resolved. Feel free to reopen if issue is still there.
